# Generated by Django 4.1.7 on 2023-04-02 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('createdate', models.DateTimeField(verbose_name='Дата создания')),
                ('is_active', models.BooleanField(verbose_name='Ативен')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Текст вопроса')),
                ('type_of_question', models.IntegerField(choices=[(0, 'Выбор'), (1, 'Дата'), (2, 'Текст')], default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveymodule.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Номер ответа')),
                ('text', models.CharField(max_length=250, verbose_name='Текст текст')),
                ('related_value', models.CharField(max_length=250, verbose_name='Связанное значение')),
                ('type_of_related_value', models.IntegerField(choices=[(0, 'Пусто'), (1, 'Строка'), (2, 'Число'), (3, 'Дата')], default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveymodule.question')),
            ],
        ),
    ]
